package exporter

type tfSchema struct {
	Name   string
	Params string
}

type tfSchemas struct {
	Schemas string
	Package string
}

var tfSchemasTemplate = `// +build !ignore_autogenerated

// Code generated by terraform-schema-gen. DO NOT EDIT.

package {{.Package}}

import "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

{{.Schemas}}
`

var schemaTemplate = `func Get{{.Name}}Schema() map[string]*schema.Schema {
return {{.Params}}
}
`
